In [4]:
import pandas as pd
!pip install openpyxl
df = pd.read_excel('customer_shopping_behavior.xlsx')

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Requirement already satisfied: openpyxl in c:\users\saran\appdata\local\programs\python\python312\lib\site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in c:\users\saran\appdata\local\programs\python\python312\lib\site-packages (from openpyxl) (2.0.0)

      Customer ID  Age  Gender Item Purchased  ... Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
0               1   55    Male         Blouse  ...             Yes                  14          Venmo            Fortnightly
1               2   19    Male        Sweater  ...             Yes                   2           Cash            Fortnightly
2               3   50    Male          Jeans  ...             Yes                  23    Credit Card                 Weekly
3               4   21    Male        Sandals  ...             Yes                  49         PayPal                 Weekly
4               5   45    Male         Blouse  ...             Yes                  31         PayPal               Annually
...           ...  ...     ...            ...  ...             ...                 ...            ...                    ...
3895         3896   40  Female         Hoodie  ...              No                  32          Venmo                 Weekly
3896         3897   52  Female       Backpack  ...              No                  41  Bank Transfer              Bi-Weekly
3897         3898   46  Female           Belt  ...              No                  24          Venmo              Quarterly
3898         3899   44  Female          Shoes  ...              No                  24          Venmo                 Weekly
3899         3900   52  Female        Handbag  ...              No                  33          Venmo              Quarterly

[3900 rows x 18 columns]

In [5]:
df.head()      # first 5 rows

   Customer ID  Age Gender Item Purchased  ... Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
0            1   55   Male         Blouse  ...             Yes                  14          Venmo            Fortnightly
1            2   19   Male        Sweater  ...             Yes                   2           Cash            Fortnightly
2            3   50   Male          Jeans  ...             Yes                  23    Credit Card                 Weekly
3            4   21   Male        Sandals  ...             Yes                  49         PayPal                 Weekly
4            5   45   Male         Blouse  ...             Yes                  31         PayPal               Annually

[5 rows x 18 columns]

In [6]:
df.tail()      # last 5 rows

      Customer ID  Age  Gender Item Purchased  ... Promo Code Used  Previous Purchases Payment Method Frequency of Purchases
3895         3896   40  Female         Hoodie  ...              No                  32          Venmo                 Weekly
3896         3897   52  Female       Backpack  ...              No                  41  Bank Transfer              Bi-Weekly
3897         3898   46  Female           Belt  ...              No                  24          Venmo              Quarterly
3898         3899   44  Female          Shoes  ...              No                  24          Venmo                 Weekly
3899         3900   52  Female        Handbag  ...              No                  33          Venmo              Quarterly

[5 rows x 18 columns]

In [7]:
df.shape       # (rows, columns)

(3900, 18)

In [8]:
df.columns     # column names

Index(['Customer ID', 'Age', 'Gender', 'Item Purchased', 'Category',
       'Purchase Amount (USD)', 'Location', 'Size', 'Color', 'Season',
       'Review Rating', 'Subscription Status', 'Shipping Type',
       'Discount Applied', 'Promo Code Used', 'Previous Purchases',
       'Payment Method', 'Frequency of Purchases'],
      dtype='str')

In [9]:
df.info()      # data types + nulls

<class 'pandas.DataFrame'>
RangeIndex: 3900 entries, 0 to 3899
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Customer ID             3900 non-null   int64
 1   Age                     3900 non-null   int64
 2   Gender                  3900 non-null   str
 3   Item Purchased          3900 non-null   str
 4   Category                3900 non-null   str
 5   Purchase Amount (USD)   3900 non-null   int64
 6   Location                3900 non-null   str
 7   Size                    3900 non-null   str
 8   Color                   3900 non-null   str
 9   Season                  3900 non-null   str
 10  Review Rating           3863 non-null   float64
 11  Subscription Status     3900 non-null   str
 12  Shipping Type           3900 non-null   str
 13  Discount Applied        3900 non-null   str
 14  Promo Code Used         3900 non-null   str
 15  Previous Purchases      3900 non-null   int64
 16  Payment Method          3900 non-null   str
 17  Frequency of Purchases  3900 non-null   str
dtypes: float64(1), int64(4), str(13)
memory usage: 548.6 KB

In [10]:
df.describe()

       Customer ID          Age  Purchase Amount (USD)  Review Rating  Previous Purchases
count  3900.000000  3900.000000            3900.000000    3863.000000         3900.000000
mean   1950.500000    44.068462              59.764359       3.750065           25.351538
std    1125.977353    15.207589              23.685392       0.716983           14.447125
min       1.000000    18.000000              20.000000       2.500000            1.000000
25%     975.750000    31.000000              39.000000       3.100000           13.000000
50%    1950.500000    44.000000              60.000000       3.800000           25.000000
75%    2925.250000    57.000000              81.000000       4.400000           38.000000
max    3900.000000    70.000000             100.000000       5.000000           50.000000

In [11]:
df.describe(include = 'all')

        Customer ID          Age Gender  ... Previous Purchases Payment Method  Frequency of Purchases
count   3900.000000  3900.000000   3900  ...        3900.000000           3900                    3900
unique          NaN          NaN      2  ...                NaN              6                       7
top             NaN          NaN   Male  ...                NaN         PayPal          Every 3 Months
freq            NaN          NaN   2652  ...                NaN            677                     584
mean    1950.500000    44.068462    NaN  ...          25.351538            NaN                     NaN
std     1125.977353    15.207589    NaN  ...          14.447125            NaN                     NaN
min        1.000000    18.000000    NaN  ...           1.000000            NaN                     NaN
25%      975.750000    31.000000    NaN  ...          13.000000            NaN                     NaN
50%     1950.500000    44.000000    NaN  ...          25.000000            NaN                     NaN
75%     2925.250000    57.000000    NaN  ...          38.000000            NaN                     NaN
max     3900.000000    70.000000    NaN  ...          50.000000            NaN                     NaN

[11 rows x 18 columns]

In [12]:
df.isnull().sum()

Customer ID                0
Age                        0
Gender                     0
Item Purchased             0
Category                   0
Purchase Amount (USD)      0
Location                   0
Size                       0
Color                      0
Season                     0
Review Rating             37
Subscription Status        0
Shipping Type              0
Discount Applied           0
Promo Code Used            0
Previous Purchases         0
Payment Method             0
Frequency of Purchases     0
dtype: int64

In [14]:
df['Review Rating'] = df.groupby('Category')['Review Rating'].transform(lambda x: x.fillna(x.median()))
df.describe(include ='all')

        Customer ID          Age Gender  ... Previous Purchases Payment Method  Frequency of Purchases
count   3900.000000  3900.000000   3900  ...        3900.000000           3900                    3900
unique          NaN          NaN      2  ...                NaN              6                       7
top             NaN          NaN   Male  ...                NaN         PayPal          Every 3 Months
freq            NaN          NaN   2652  ...                NaN            677                     584
mean    1950.500000    44.068462    NaN  ...          25.351538            NaN                     NaN
std     1125.977353    15.207589    NaN  ...          14.447125            NaN                     NaN
min        1.000000    18.000000    NaN  ...           1.000000            NaN                     NaN
25%      975.750000    31.000000    NaN  ...          13.000000            NaN                     NaN
50%     1950.500000    44.000000    NaN  ...          25.000000            NaN                     NaN
75%     2925.250000    57.000000    NaN  ...          38.000000            NaN                     NaN
max     3900.000000    70.000000    NaN  ...          50.000000            NaN                     NaN

[11 rows x 18 columns]

In [15]:
df.isnull().sum()

Customer ID               0
Age                       0
Gender                    0
Item Purchased            0
Category                  0
Purchase Amount (USD)     0
Location                  0
Size                      0
Color                     0
Season                    0
Review Rating             0
Subscription Status       0
Shipping Type             0
Discount Applied          0
Promo Code Used           0
Previous Purchases        0
Payment Method            0
Frequency of Purchases    0
dtype: int64

In [29]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.replace(' ', '_')

In [30]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount_(usd)', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [37]:
df = df.rename(columns = {'purchase_amount_(usd)' : 'purchase_amount'})
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'promo_code_used', 'previous_purchases',
       'payment_method', 'frequency_of_purchases'],
      dtype='str')

In [39]:
# create a column age_group
labels =  ['Young Adult', 'Adult', 'Middle-aged', 'Senior']
df['age_group'] = pd.qcut (df['age'], q=4, labels = labels)

In [45]:
df['age_group'].value_counts()

age_group
Young Adult    1028
Middle-aged     986
Senior          944
Adult           942
Name: count, dtype: int64

In [47]:
df[['age','age_group']].head(10)

   age    age_group
0   55  Middle-aged
1   19  Young Adult
2   50  Middle-aged
3   21  Young Adult
4   45  Middle-aged
5   46  Middle-aged
6   63       Senior
7   27  Young Adult
8   26  Young Adult
9   57  Middle-aged

In [50]:
# Create column purchase_frequency_days
frequency_mapping = {
    'Fortnightly' : 14,
    'Weekly': 7,
    'Monthly': 30,
    'Quarterly':90,
    'Bi-Weekly': 14,
    'Annually': 365,
    'Every 3 months': 90
}

df['purchase_frequency_days'] = df['frequency_of_purchases'].map(frequency_mapping)

In [52]:
df['frequency_of_purchases'].value_counts()

frequency_of_purchases
Every 3 Months    584
Annually          572
Quarterly         563
Monthly           553
Bi-Weekly         547
Fortnightly       542
Weekly            539
Name: count, dtype: int64

In [53]:
df['purchase_frequency_days'].value_counts()

purchase_frequency_days
14.0     1089
365.0     572
90.0      563
30.0      553
7.0       539
Name: count, dtype: int64

In [54]:
df['frequency_of_purchases'].head(10)

0    Fortnightly
1    Fortnightly
2         Weekly
3         Weekly
4       Annually
5         Weekly
6      Quarterly
7         Weekly
8       Annually
9      Quarterly
Name: frequency_of_purchases, dtype: str

In [55]:
df['purchase_frequency_days'].isnull().sum()

np.int64(584)

In [59]:
(df['discount_applied'] == df['promo_code_used']).all()

np.True_

In [63]:
df = df.drop('promo_code_used', axis = 1)

KeyError: "['promo_code_used'] not found in axis"

In [62]:
df

      customer_id  age  gender  ... frequency_of_purchases    age_group  purchase_frequency_days
0               1   55    Male  ...            Fortnightly  Middle-aged                     14.0
1               2   19    Male  ...            Fortnightly  Young Adult                     14.0
2               3   50    Male  ...                 Weekly  Middle-aged                      7.0
3               4   21    Male  ...                 Weekly  Young Adult                      7.0
4               5   45    Male  ...               Annually  Middle-aged                    365.0
...           ...  ...     ...  ...                    ...          ...                      ...
3895         3896   40  Female  ...                 Weekly        Adult                      7.0
3896         3897   52  Female  ...              Bi-Weekly  Middle-aged                     14.0
3897         3898   46  Female  ...              Quarterly  Middle-aged                     90.0
3898         3899   44  Female  ...                 Weekly        Adult                      7.0
3899         3900   52  Female  ...              Quarterly  Middle-aged                     90.0

[3900 rows x 19 columns]

In [65]:
pip install psycopg2-binary sqlalchemy

Collecting psycopg2-binary
  Downloading psycopg2_binary-2.9.11-cp312-cp312-win_amd64.whl.metadata (5.1 kB)
Collecting sqlalchemy
  Downloading sqlalchemy-2.0.49-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Downloading greenlet-3.3.2-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\saran\appdata\local\programs\python\python312\lib\site-packages (from sqlalchemy) (4.15.0)
Downloading psycopg2_binary-2.9.11-cp312-cp312-win_amd64.whl (2.7 MB)
   ---------------------------------------- 0.0/2.7 MB ? eta -:--:--
   ------- -------------------------------- 0.5/2.7 MB 5.7 MB/s eta 0:00:01
   ---------------------------------- ----- 2.4/2.7 MB 7.5 MB/s eta 0:00:01
   ---------------------------------------- 2.7/2.7 MB 7.1 MB/s eta 0:00:00
Downloading sqlalchemy-2.0.49-cp312-cp312-win_amd64.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------- ----- 1.8/2.1 MB 10.1 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 10.1 MB/s eta 0:00:00
Downloading greenlet-3.3.2-cp312-cp312-win_amd64.whl (231 kB)
Installing collected packages: psycopg2-binary, greenlet, sqlalchemy
Successfully installed greenlet-3.3.2 psycopg2-binary-2.9.11 sqlalchemy-2.0.49
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.0.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [70]:
!python.exe -m pip install --upgrade pip

Requirement already satisfied: pip in c:\users\saran\appdata\local\programs\python\python312\lib\site-packages (25.0.1)
Collecting pip
  Using cached pip-26.0.1-py3-none-any.whl.metadata (4.7 kB)
Using cached pip-26.0.1-py3-none-any.whl (1.8 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 25.0.1
    Uninstalling pip-25.0.1:
      Successfully uninstalled pip-25.0.1
Successfully installed pip-26.0.1

In [77]:
#Step 1: Connect to PostgreSQL
# Replace placeholders with your actual details
from sqlalchemy import create_engine
username = "postgres" # default user
password = "Saransh@2210" # the password you set during installation
host = "localhost" # if running Locally
port ="5432" # default PostgreSQL port
database = "customer_behaviour" # the database you created in pgAdmin
engine = create_engine(f"postgresql+psycopg2://{username}: {password}@{host}: {port}/{database}")
# Step 2: Load DataFrame into PostgreSQL
table_name = "customer" # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)
print (f"Data successfully loaded into table '{table_name}' in database '{database}'.")

OperationalError: (psycopg2.OperationalError) could not translate host name "2210@localhost" to address: Non-recoverable failure in name resolution

(Background on this error at: https://sqlalche.me/e/20/e3q8)

In [78]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

username = "postgres"
password = quote_plus("Saransh@2210")
host = "localhost"
port = "5432"
database = "customer_behaviour"

engine = create_engine(f"postgresql+psycopg2://{username}:{password}@{host}:{port}/{database}")
# Step 2: Load DataFrame into PostgreSQL
table_name = "customer" # choose any table name
df.to_sql(table_name, engine, if_exists="replace", index=False)
print (f"Data successfully loaded into table '{table_name}' in database '{database}'.")

Data successfully loaded into table 'customer' in database 'customer_behaviour'.

In [79]:
df.columns

Index(['customer_id', 'age', 'gender', 'item_purchased', 'category',
       'purchase_amount', 'location', 'size', 'color', 'season',
       'review_rating', 'subscription_status', 'shipping_type',
       'discount_applied', 'previous_purchases', 'payment_method',
       'frequency_of_purchases', 'age_group', 'purchase_frequency_days'],
      dtype='str')

In [80]:
df

      customer_id  age  gender  ... frequency_of_purchases    age_group  purchase_frequency_days
0               1   55    Male  ...            Fortnightly  Middle-aged                     14.0
1               2   19    Male  ...            Fortnightly  Young Adult                     14.0
2               3   50    Male  ...                 Weekly  Middle-aged                      7.0
3               4   21    Male  ...                 Weekly  Young Adult                      7.0
4               5   45    Male  ...               Annually  Middle-aged                    365.0
...           ...  ...     ...  ...                    ...          ...                      ...
3895         3896   40  Female  ...                 Weekly        Adult                      7.0
3896         3897   52  Female  ...              Bi-Weekly  Middle-aged                     14.0
3897         3898   46  Female  ...              Quarterly  Middle-aged                     90.0
3898         3899   44  Female  ...                 Weekly        Adult                      7.0
3899         3900   52  Female  ...              Quarterly  Middle-aged                     90.0

[3900 rows x 19 columns]